environment:
  nodejs_version: 11.1.0

platform:
  - x86

install:
  - ps: Install-Product node $env:nodejs_version
  - cinst -y nsis
  - SET PATH=C:\Program Files\NSIS\;C:\Program Files (x86)\NSIS\;%PATH%
  - (New-Object Net.WebClient).DownloadFile("https://yarnpkg.com/latest.msi", "$env:temp\yarn.msi")
  - cmd /c start /wait msiexec.exe /i $env:temp\yarn.msi /quiet /qn /norestart
  - yarn
build_script:
  - cmd: node lib\scripts\packageDesktopApp.js

test_script:
  - node --version
  - npm --version
  - yarn --version

artifacts:
  - path: nwjs-out\versions\**\*
    name: build

version: "{build}"

skip_tags: true

deploy:
  - provider: S3
    access_key_id:
      secure: AkqgS6TgE6nC0WUZ3nNtqoH1LkPOYhol/bSlMRleKcg=
    secret_access_key:
      secure: 8hFJeMNTHobCOn8OkZirlb3iCEGjUHtxsWSFv3Jo79nklT34asKfOVcFzf3WJ1/B
    bucket: quirkbot-downloads-stage
    region: us-east-1
    set_public: true
    folder: nwjs-build
    artifact: build
    on:
      branch: develop
  - provider: S3
    access_key_id:
      secure: AkqgS6TgE6nC0WUZ3nNtqoH1LkPOYhol/bSlMRleKcg=
    secret_access_key:
      secure: 8hFJeMNTHobCOn8OkZirlb3iCEGjUHtxsWSFv3Jo79nklT34asKfOVcFzf3WJ1/B
    bucket: quirkbot-downloads-production
    region: us-east-1
    set_public: true
    folder: nwjs-build
    artifact: build
    on:
      branch: master
